### ISSUE TITLE
Switch default branch from master to main?

### ISSUE THREAD

**Issue by felixfontein** [ansible/acme-test-container#20]
@mattclay would it be ok for you to change the default branch of this repo from master to main? I think there's not much that needs to be done (since nothing really depends on the name of the master branch in this repo), mainly a) push the new `main` branch, b) switch the default branch, c) delete the old `master` branch, and d) adjust the default branch in shippable.

**Comment by mattclay** [comment]
We'll also need to make sure the quay.io builds trigger and work correctly after the changes.

To simplify management of all of the `*-test-container*` repos I'd like to maintain consistent configuration/workflow for them as much as possible, but that does mean a bigger change. I have it on my list to do, but don't know when I'll get to it.

**Comment by felixfontein** [comment]
@mattclay sounds good to me! Just wanted to avoid that this falls through the cracks.

**Comment by mattclay** [comment]
The default branch has been updated.

**Comment by felixfontein** [comment]
Thanks!
